#ifndef SHOEUTILSLIBRARY_GLOBAL_H
#define SHOEUTILSLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SHOEUTILSLIBRARY_LIBRARY)
#  define SHOEUTILSLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SHOEUTILSLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOEUTILSLIBRARY_GLOBAL_H
