#ifndef SHOECOMMLIBRARY_GLOBAL_H
#define SHOECOMMLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SHOECOMMLIBRARY_LIBRARY)
#  define SHOECOMMLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SHOECOMMLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOECOMMLIBRARY_GLOBAL_H
